/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosticIndexRouteImport } from './routes/diagnostic.index'
import { Route as TalentsMapRouteImport } from './routes/talents.map'
import { Route as DiagnosticResultRouteImport } from './routes/diagnostic.result'
import { Route as DiagnosticQuestionsRouteImport } from './routes/diagnostic.questions'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticIndexRoute = DiagnosticIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiagnosticRoute,
} as any)
const TalentsMapRoute = TalentsMapRouteImport.update({
  id: '/talents/map',
  path: '/talents/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticResultRoute = DiagnosticResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => DiagnosticRoute,
} as any)
const DiagnosticQuestionsRoute = DiagnosticQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => DiagnosticRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/diagnostic/questions': typeof DiagnosticQuestionsRoute
  '/diagnostic/result': typeof DiagnosticResultRoute
  '/talents/map': typeof TalentsMapRoute
  '/diagnostic/': typeof DiagnosticIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/diagnostic/questions': typeof DiagnosticQuestionsRoute
  '/diagnostic/result': typeof DiagnosticResultRoute
  '/talents/map': typeof TalentsMapRoute
  '/diagnostic': typeof DiagnosticIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/diagnostic/questions': typeof DiagnosticQuestionsRoute
  '/diagnostic/result': typeof DiagnosticResultRoute
  '/talents/map': typeof TalentsMapRoute
  '/diagnostic/': typeof DiagnosticIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostic'
    | '/welcome'
    | '/diagnostic/questions'
    | '/diagnostic/result'
    | '/talents/map'
    | '/diagnostic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome'
    | '/diagnostic/questions'
    | '/diagnostic/result'
    | '/talents/map'
    | '/diagnostic'
  id:
    | '__root__'
    | '/'
    | '/diagnostic'
    | '/welcome'
    | '/diagnostic/questions'
    | '/diagnostic/result'
    | '/talents/map'
    | '/diagnostic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticRoute: typeof DiagnosticRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  TalentsMapRoute: typeof TalentsMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic/': {
      id: '/diagnostic/'
      path: '/'
      fullPath: '/diagnostic/'
      preLoaderRoute: typeof DiagnosticIndexRouteImport
      parentRoute: typeof DiagnosticRoute
    }
    '/talents/map': {
      id: '/talents/map'
      path: '/talents/map'
      fullPath: '/talents/map'
      preLoaderRoute: typeof TalentsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic/result': {
      id: '/diagnostic/result'
      path: '/result'
      fullPath: '/diagnostic/result'
      preLoaderRoute: typeof DiagnosticResultRouteImport
      parentRoute: typeof DiagnosticRoute
    }
    '/diagnostic/questions': {
      id: '/diagnostic/questions'
      path: '/questions'
      fullPath: '/diagnostic/questions'
      preLoaderRoute: typeof DiagnosticQuestionsRouteImport
      parentRoute: typeof DiagnosticRoute
    }
  }
}

interface DiagnosticRouteChildren {
  DiagnosticQuestionsRoute: typeof DiagnosticQuestionsRoute
  DiagnosticResultRoute: typeof DiagnosticResultRoute
  DiagnosticIndexRoute: typeof DiagnosticIndexRoute
}

const DiagnosticRouteChildren: DiagnosticRouteChildren = {
  DiagnosticQuestionsRoute: DiagnosticQuestionsRoute,
  DiagnosticResultRoute: DiagnosticResultRoute,
  DiagnosticIndexRoute: DiagnosticIndexRoute,
}

const DiagnosticRouteWithChildren = DiagnosticRoute._addFileChildren(
  DiagnosticRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticRoute: DiagnosticRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  TalentsMapRoute: TalentsMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
